version: "3"
services:
  app:
    restart: always
    build: .  # '点'代表当前目录
    #command: "python3 manage.py runserver 0.0.0.0:8001"
    command: bash -c "uwsgi --ini uwsgi.ini"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
